import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import connectMongo from '../../utils/connectMongo';
import Test from '../../models/testModel';
import Auth from '../../components/layouts/Auth'
import { useState } from 'react';


export const getServerSideProps = async () => {
    try {
        console.log('CONNECTING TO MONGO');
        await connectMongo();
        console.log('CONNECTED TO MONGO');

        console.log('FETCHING DOCUMENTS');
        const tests = await Test.find();
        console.log('FETCHED DOCUMENTS');

        return {
            props: {
                data: JSON.parse(JSON.stringify(tests)),
            },
        };
    } catch (error) {
        console.log(error);
        return {
            notFound: true,
        };
    }
};

export default function Home({ data }) {
    const [formData, setFormData] = useState({})
    const handleInput = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value })
    }
    const createTest = async () => {
        const randomNum = Math.floor(Math.random() * 1000);
        const res = await fetch('/api/test/add', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                name: formData.name,
                email: formData.email,
            }),
        });
        const data = await res.json();
        console.log(data);
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>
                <form onSubmit={createTest}>
                    <div className="flex flex-col gap-4">
                        <input onChange={handleInput} type="text" name='name' id='name' placeholder='Name' />
                        <input onChange={handleInput} type="text" name='email' id='email' placeholder='Email' />
                        <button className='bg-blue-500 rounded-md p-4 hover:bg-blue-600 text-white' type='submit'>Create Test</button>
                    </div>
                </form>

                <div className={styles.grid}>
                    {data.map((user) => (
                        <a
                            href="https://nextjs.org/docs"
                            key={user._id}
                            className={styles.card}
                        >
                            <h2>{user.name} &rarr;</h2>
                            <p>{user.email}</p>
                        </a>
                    ))}
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
                    target='_blank'
                    rel='noopener noreferrer'
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
}
Home.layout = Auth;
