const data = {
  users: [
    {
      fname: "Nitin",
      lname: "Khandelwal",
      cname: "Signagewala",
      email: "signagewala.com@gmail.com",
      mobile: 9818866966,
      pass: "s123",
      type: "admin",
      status: "approved",
    },
    {
      fname: "Joseph",
      lname: "Vijay",
      cname: "Infinity Retail Pvt Ltd",
      email: "joseph@croma.com",
      mobile: 9818379227,
      pass: "c123",
      type: "corp",
      status: "approved",
      rates: [
        {
          description: "3mm Acrylic",
          rate: 70,
          unit: "Sqft",
          measureunit: "Inches",
          calcfactor: 144,
          status: "requested",
        },
        {
          description: "3mm Sunboard",
          rate: 19,
          unit: "Sqft",
          measureunit: "Inches",
          calcfactor: 144,
          status: "requested",
        },
        {
          description: "5mm Acrylic",
          rate: 120,
          unit: "Sqft",
          measureunit: "Inches",
          calcfactor: 144,
          status: "requested",
        },
        {
          description: "5mm Sunboard",
          rate: 32,
          unit: "Sqft",
          measureunit: "Inches",
          calcfactor: 144,
          status: "requested",
        },
        {
          description: "Clear Vinyl (Vynl) | Avery | Eco-Solvent Printing",
          rate: 10,
          unit: "Sqft",
          measureunit: "Inches",
          status: "approved",
        },
        {
          description: "Clear Vinyl (Vynl) | Avery | Latex Printing",
          rate: 60,
          unit: "Sqft",
          measureunit: "Inches",
          status: "approved",
        },
        {
          description: "Clear Vinyl (Vynl) | Avery | Solvent Printing",
          rate: 15,
          unit: "Sqft",
          measureunit: "Inches",
          status: "approved",
        },
        {
          description: "Clear Vinyl (Vynl) | Eco-Solvent Printing",
          rate: 8,
          unit: "Sqft",
          measureunit: "Inches",
          status: "approved",
        },
        {
          description: "Clear Vinyl (Vynl) | Latex Printing",
          rate: 10,
          unit: "Sqft",
          measureunit: "Inches",
          status: "approved",
        },
        {
          description: "Clear Vinyl (Vynl) | LG | Latex Printing",
          rate: 10,
          unit: "Sqft",
          measureunit: "Inches",
          status: "approved",
        },
        {
          description: "Clear Vinyl (Vynl) | LG | Solvent Printing",
          rate: 11,
          unit: "Sqft",
          measureunit: "Inches",
          status: "approved",
        },
      ],
    },
    {
      fname: "Manoj",
      lname: "Sharma",
      cname: "Sharma Arts",
      email: "sharmaarts@gmil.com",
      mobile: 7042866966,
      pass: "s123",
      type: "vend",
      status: "approved",
    },
    {
      fname: "Mukul",
      lname: "Awasthi",
      cname: "Reliance Trends",
      email: "mukul@trends.com",
      mobile: 9810132460,
      pass: "r123",
      type: "corp",
      status: "pending",
    },
    {
      fname: "Ajay",
      lname: "Bisht",
      cname: "Artlin Nashik",
      email: "ajay@artline.com",
      mobile: 9811757401,
      pass: "a123",
      type: "vend",
      status: "suspended",
    },
  ],
  authnavmenu: [
    {
      lable: "Login",
      url: "/auth/login",
    },
    {
      lable: "Register",
      url: "/auth/register",
    },
  ],
  adminroutes: [
    {
      lable: "Dashboard",
      url: "/user/admin/dashboard",
      icon: "fa-solid fa-gauge-high",
    },
    {
      lable: "Rates",
      url: "/user/admin/rates",
      icon: "fa-solid fa-money-check-dollar",
    },
    {
      lable: "Subscribers",
      url: "/user/admin/subscribers",
      icon: "fa-solid fa-users-viewfinder",
    },
  ],
  corproutes: [
    {
      lable: "Dashboard",
      url: "/user/corp/dashboard",
      icon: "fa-solid fa-gauge-high",
    },
    {
      lable: "Profile",
      url: "/user/corp/profile",
      icon: "fa-solid fa-id-card-clip",
    },
    {
      lable: "Stores",
      url: "/user/corp/stores",
      icon: "fa-solid fa-store",
    },
    {
      lable: "Rates",
      url: "/user/corp/rates",
      icon: "fa-solid fa-money-check-dollar",
    },
  ],
  generalratecard: [
    {
      description: "3mm Acrylic",
      rate: 70,
      unit: "Sqft",
      measureunit: "inches",
      calcfactor: 144,
    },
    {
      description: "3mm Sunboard",
      rate: 19,
      unit: "Sqft",
      measureunit: "feet",
      calcfactor: 144,
    },
    {
      description: "5mm Acrylic",
      rate: 120,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "5mm Sunboard",
      rate: 32,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clear Vinyl (Vynl)",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clear Vinyl (Vynl) | Avery",
      rate: 34,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clear Vinyl (Vynl) | Avery | Eco-Solvent Printing",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clear Vinyl (Vynl) | Avery | Latex Printing",
      rate: 72,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clear Vinyl (Vynl) | Avery | Solvent Printing",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clear Vinyl (Vynl) | Eco-Solvent Printing",
      rate: 10,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clear Vinyl (Vynl) | Latex Printing",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clear Vinyl (Vynl) | LG",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clear Vinyl (Vynl) | LG | Eco-Solvent Printing",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clear Vinyl (Vynl) | LG | Latex Printing",
      rate: 11,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clear Vinyl (Vynl) | LG | Solvent Printing",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clear Vinyl (Vynl) | Solvent Printing",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clipon P1 Lit Structure With Translit Eco-Print",
      rate: 693,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clipon P1 Non-Lit Structure With Translit Eco-Print",
      rate: 299,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clipon P2 Lit Structure With Translit Eco-Print",
      rate: 693,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clipon P2 Non-Lit Structure With Translit Eco-Print",
      rate: 299,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clipon P3 Lit Structure With Translit Eco-Print",
      rate: 693,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Clipon P3 Non-Lit Structure With Translit Eco-Print",
      rate: 299,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex",
      rate: 9,
      unit: "Sqft",
      measureunit: "inches",
      img: "/img/sign.jpg",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit",
      rate: 18,
      unit: "Sqft",
      measureunit: "feet",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | Avery",
      rate: 17,
      unit: "Sqft",
      measureunit: "runningInch",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | Avery | Eco-Solvent Printing",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | Avery | Latex Printing",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | Avery | Solvent Printing",
      rate: 24,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | Avery | UV Printing",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | Eco-Solvent Printing",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | Latex Printing",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | LG",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | LG | Eco-Solvent Printing",
      rate: 13,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | LG | Latex Printing",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | LG | Solvent Printing",
      rate: 32,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | LG | UV Printing",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | Solvent Printing",
      rate: 18,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | Star",
      rate: 20,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | Star | Eco-Solvent Printing",
      rate: 120,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | Star | Latex Printing",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | Star | Solvent Printing",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | Star | UV Printing",
      rate: 9,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Backlit | UV Printing",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback",
      rate: 10,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | Avery",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | Avery | Eco-Solvent Printing",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | Avery | Latex Printing",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | Avery | Solvent Printing",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | Avery | UV Printing",
      rate: 18,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | Eco-Solvent Printing",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | Latex Printing",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | LG",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | LG | Eco-Solvent Printing",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | LG | Latex Printing",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | LG | Solvent Printing",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | LG | UV Printing",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | Solvent Printing",
      rate: 10,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | Star",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | Star | Eco-Solvent Printing",
      rate: 70,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | Star | Latex Printing",
      rate: 20,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | Star | Solvent Printing",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | Star | UV Printing",
      rate: 72,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex - Blackback | UV Printing",
      rate: 11,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | Avery",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | Avery | Eco-Solvent Printing",
      rate: 11,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | Avery | Latex Printing",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | Avery | Solvent Printing",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | Avery | UV Printing",
      rate: 10,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | Eco-Solvent Printing",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | Latex Printing",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | LG",
      rate: 11,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | LG | Eco-Solvent Printing",
      rate: 18,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | LG | Latex Printing",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | LG | Solvent Printing",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | LG | UV Printing",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | Solvent Printing",
      rate: 9,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | Star",
      rate: 11,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | Star | Eco-Solvent Printing",
      rate: 32,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | Star | Latex Printing",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | Star | Solvent Printing",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | Star | UV Printing",
      rate: 34,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Flex | UV Printing",
      rate: 24,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl)",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | Avery",
      rate: 21,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | Avery | Eco-Solvent Printing",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | Avery | Eco-Solvent Printing | Gloss Lamination",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | Avery | Eco-Solvent Printing | Matte Lamination",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | Avery | Latex Printing",
      rate: 34,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | Avery | Latex Printing | Gloss Lamination",
      rate: 72,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | Avery | Latex Printing | Matte Lamination",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | Avery | Solvent Printing",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | Avery | Solvent Printing | Gloss Lamination",
      rate: 70,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | Avery | Solvent Printing | Matte Lamination",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | Avery | UV Printing",
      rate: 20,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | Avery | UV Printing | Gloss Lamination",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | Avery | UV Printing | Matte Lamination",
      rate: 20,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | Eco-Solvent Printing",
      rate: 9,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | Eco-Solvent Printing | Gloss Lamination",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | Eco-Solvent Printing | Matte Lamination",
      rate: 32,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | Latex Printing",
      rate: 11,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | Latex Printing | Gloss Lamination",
      rate: 24,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | Latex Printing | Matte Lamination",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | LG",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | LG | Eco-Solvent Printing",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | LG | Eco-Solvent Printing | Gloss Lamination",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | LG | Eco-Solvent Printing | Matte Lamination",
      rate: 11,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | LG | Latex Printing",
      rate: 24,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | LG | Latex Printing | Gloss Lamination",
      rate: 72,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | LG | Latex Printing | Matte Lamination",
      rate: 9,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | LG | Solvent Printing",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | LG | Solvent Printing | Gloss Lamination",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Frosted Vinyl (Vynl) | LG | Solvent Printing | Matte Lamination",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | LG | UV Printing",
      rate: 21,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | LG | UV Printing | Gloss Lamination",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | LG | UV Printing | Matte Lamination",
      rate: 24,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | Solvent Printing",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | Solvent Printing | Gloss Lamination",
      rate: 20,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | Solvent Printing | Matte Lamination",
      rate: 18,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | UV Printing",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | UV Printing | Gloss Lamination",
      rate: 11,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Frosted Vinyl (Vynl) | UV Printing | Matte Lamination",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "OneWay Vision",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "OneWay Vision | Avery",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "OneWay Vision | Avery | Eco-Solvent Printing",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "OneWay Vision | Avery | Latex Printing",
      rate: 24,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "OneWay Vision | Avery | Solvent Printing",
      rate: 20,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "OneWay Vision | Eco-Solvent Printing",
      rate: 34,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "OneWay Vision | Latex Printing",
      rate: 70,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "OneWay Vision | LG",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "OneWay Vision | LG | Eco-Solvent Printing",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "OneWay Vision | LG | Latex Printing",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "OneWay Vision | LG | Solvent Printing",
      rate: 11,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "OneWay Vision | Solvent Printing",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Recce",
      width: 0,
      height: 0,
      rate: 500,
      unit: "Sqft",
      measureunit: "Store",
    },
    {
      description: "Reflective Vinyl (Vynl)",
      rate: 20,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Reflective Vinyl (Vynl) | Avery",
      rate: 24,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Reflective Vinyl (Vynl) | Avery | Eco-Solvent Printing",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Reflective Vinyl (Vynl) | Avery | Latex Printing",
      rate: 21,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Reflective Vinyl (Vynl) | Avery | Solvent Printing",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Reflective Vinyl (Vynl) | Eco-Solvent Printing",
      rate: 72,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Reflective Vinyl (Vynl) | Latex Printing",
      rate: 120,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Reflective Vinyl (Vynl) | LG",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Reflective Vinyl (Vynl) | LG | Eco-Solvent Printing",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Reflective Vinyl (Vynl) | LG | Latex Printing",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Reflective Vinyl (Vynl) | LG | Solvent Printing",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Reflective Vinyl (Vynl) | Solvent Printing",
      rate: 20,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Roll up Standee 3ft x 6ft Eco-Print Normal Flex",
      width: 36,
      height: 72,
      rate: 1200,
      unit: "Pc",
      img: "/img/rollup.jpg",
      measureunit: "Inches",
    },
    {
      description: "Roll up Standee 3ft x 6ft Eco-Print PET Film",
      width: 36,
      height: 72,
      rate: 2500,
      unit: "Pc",
      img: "/img/rollup.jpg",
      measureunit: "Inches",
    },
    {
      description: "Roll up Standee 3ft x 6ft Solvent Normal Flex",
      width: 36,
      height: 72,
      rate: 800,
      unit: "Pc",
      img: "/img/rollup.jpg",
      measureunit: "Inches",
    },
    {
      description: "Roll up Standee 3ft x 6ft Solvent PET Film",
      width: 36,
      height: 72,
      rate: 1800,
      unit: "Pc",
      img: "/img/rollup.jpg",
      measureunit: "Inches",
    },
    {
      description: "Translite",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Translite | Avery",
      rate: 72,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Translite | LG",
      rate: 24,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl)",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback",
      rate: 13,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | Avery",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | Avery | Eco-Solvent Printing",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | Avery | Eco-Solvent Printing | Gloss Lamination",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | Avery | Eco-Solvent Printing | Matte Lamination",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | Avery | Latex Printing",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | Avery | Latex Printing | Gloss Lamination",
      rate: 34,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | Avery | Latex Printing | Matte Lamination",
      rate: 18,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | Avery | Solvent Printing",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | Avery | Solvent Printing | Gloss Lamination",
      rate: 32,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | Avery | Solvent Printing | Matte Lamination",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | Avery | UV Printing",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | Avery | UV Printing | Gloss Lamination",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | Avery | UV Printing | Matte Lamination",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | Eco-Solvent Printing",
      rate: 21,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | Eco-Solvent Printing | Gloss Lamination",
      rate: 11,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | Eco-Solvent Printing | Matte Lamination",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | Latex Printing",
      rate: 32,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | Latex Printing | Gloss Lamination",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | Latex Printing | Matte Lamination",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | LG",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | LG | Eco-Solvent Printing",
      rate: 20,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | LG | Eco-Solvent Printing | Gloss Lamination",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | LG | Eco-Solvent Printing | Matte Lamination",
      rate: 120,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | LG | Latex Printing",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | LG | Latex Printing | Gloss Lamination",
      rate: 34,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | LG | Latex Printing | Matte Lamination",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | LG | Solvent Printing",
      rate: 120,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | LG | Solvent Printing | Gloss Lamination",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | LG | Solvent Printing | Matte Lamination",
      rate: 13,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | LG | UV Printing",
      rate: 24,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | LG | UV Printing | Gloss Lamination",
      rate: 20,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | LG | UV Printing | Matte Lamination",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | Solvent Printing",
      rate: 13,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | Solvent Printing | Gloss Lamination",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) - Greyback | Solvent Printing | Matte Lamination",
      rate: 10,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | UV Printing",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | UV Printing | Gloss Lamination",
      rate: 24,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) - Greyback | UV Printing | Matte Lamination",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Avery",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Avery | Eco-Solvent Printing",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) | Avery | Eco-Solvent Printing | Gloss Lamination",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) | Avery | Eco-Solvent Printing | Matte Lamination",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Avery | Latex Printing",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Avery | Latex Printing | Gloss Lamination",
      rate: 21,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Avery | Latex Printing | Matte Lamination",
      rate: 10,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Avery | Solvent Printing",
      rate: 11,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Avery | Solvent Printing | Gloss Lamination",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Avery | Solvent Printing | Matte Lamination",
      rate: 20,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Avery | UV Printing",
      rate: 13,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Avery | UV Printing | Gloss Lamination",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Avery | UV Printing | Matte Lamination",
      rate: 11,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Eco-Solvent Printing",
      rate: 24,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Eco-Solvent Printing | Gloss Lamination",
      rate: 120,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Eco-Solvent Printing | Matte Lamination",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Latex Printing",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Latex Printing | Gloss Lamination",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Latex Printing | Matte Lamination",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | LG",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | LG | Eco-Solvent Printing",
      rate: 15,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) | LG | Eco-Solvent Printing | Gloss Lamination",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description:
        "Vinyl (Vynl) | LG | Eco-Solvent Printing | Matte Lamination",
      rate: 70,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | LG | Latex Printing",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | LG | Latex Printing | Gloss Lamination",
      rate: 21,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | LG | Latex Printing | Matte Lamination",
      rate: 22,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | LG | Solvent Printing",
      rate: 70,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | LG | Solvent Printing | Gloss Lamination",
      rate: 17,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | LG | Solvent Printing | Matte Lamination",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | LG | UV Printing",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | LG | UV Printing | Gloss Lamination",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | LG | UV Printing | Matte Lamination",
      rate: 19,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Solvent Printing",
      rate: 12,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Solvent Printing | Gloss Lamination",
      rate: 13,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | Solvent Printing | Matte Lamination",
      rate: 9,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | UV Printing",
      rate: 20,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | UV Printing | Gloss Lamination",
      rate: 14,
      unit: "Sqft",
      measureunit: "Inches",
      calcfactor: 144,
    },
    {
      description: "Vinyl (Vynl) | UV Printing | Matte Lamination",
      rate: 15,
      unit: "Sqft",
      measureunit: "inches",
      calcfactor: 144,
    },
    {
      description: "Wooden Easel Stand",
      width: 0,
      height: 0,
      rate: 800,
      unit: "Pc",
      img: "/img/woodenstand.jpg",
      measureunit: "",
    },
  ],
};
export default data;
